# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 11:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtfLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
                ('unlock_key', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('target_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('value', models.IntegerField(default=0)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.CtfLevel')),
            ],
        ),
        migrations.CreateModel(
            name='FlagFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(default='')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Flag')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=25)),
                ('score', models.IntegerField(default=0)),
                ('CtfLevels', models.CharField(default='0', max_length=50, validators=[django.core.validators.int_list_validator])),
                ('QuizLevels', models.CharField(default='0', max_length=50, validators=[django.core.validators.int_list_validator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('question_text', models.TextField(default='')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_on', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='')),
                ('unlock_key', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.QuizLevel'),
        ),
        migrations.AddField(
            model_name='flagfind',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Player'),
        ),
    ]
