# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 08:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='CtfLevels',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
